"""empty message

Revision ID: 148c920e720a
Revises: 41281ad191e9
Create Date: 2014-09-28 02:11:07.429000

"""

# revision identifiers, used by Alembic.
revision = '148c920e720a'
down_revision = '41281ad191e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('i_univ', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('i_univ', sa.Column('term', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('i_univ', 'term')
    op.drop_column('i_univ', 'photo')
    ### end Alembic commands ###
