"""empty message

Revision ID: 196d53a821a4
Revises: None
Create Date: 2014-09-23 16:30:26.068000

"""

# revision identifiers, used by Alembic.
revision = '196d53a821a4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('pw', sa.String(length=255), nullable=True),
    sa.Column('univname', sa.String(length=255), nullable=True),
    sa.Column('avg_credit', sa.Integer(), nullable=True),
    sa.Column('eng_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    ### end Alembic commands ###
