"""empty message

Revision ID: 41281ad191e9
Revises: 4630d5b91386
Create Date: 2014-09-25 19:59:42.683000

"""

# revision identifiers, used by Alembic.
revision = '41281ad191e9'
down_revision = '4630d5b91386'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('i_univ', sa.Column('date_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('i_univ', 'date_created')
    ### end Alembic commands ###
